apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: Party Interaction Management
    oda.tmforum.org/funtionalBlockName: Party Management
  name: TAG_REALESE_NAME - Party Interaction Management
spec:
  componentKinds:
  - group: core
    kind: Catalog
  coreFunction:
    exposedAPIs:
        - PartyInteractionManagement:
              version: 4.0
              id: TMF683
              PartyInteraction:
                    - GET
                    - GET /id
                    - POST
                    - PATCH / id
                    - DELETE
        - ProcessFlowManagement:
            version: 4.0
            id: TMF701
            processFlow:
                - POST
                - GET
                - GET /id
                - DELETE
            taskFlow:
                - PATCH
                - GET
                - GET /id
 
        - Event:
            version: 4.0
            id: TMF688
            listener:
                - POST
            hub:
                - POST
                - DELETE
    dependantAPIs:
        - PartyManagement:
              version: 4.0
              id: TMF632
              Individual:
                    - GET
                    - GET /id
        - PartyRoleManagement:
              version: 4.0
              id: TMF669
              PartyRole:
                    - GET
                    - GET /id               
        - UserRolesAndPermission:
              version: 4.0
              id: TMF672
              Permission:
                    - GET
                    - GET /id
        - EntityCatalogManagement:
              version: 4.0
              id: TMF662
              EntityCatalog:
                    - GET
                    - GET /id
 
              EntityCategory:
                    - GET
                    - GET /id     
              EntityCatalogItem:
                    - GET
                    - GET /id       
              EntitySpecification:
                    - GET
                    - GET /id     
        - DocumentgManagement:
              version: 4.0
              id: TMF667
              Document:
                    - GET
                    - GET /id                   
        - Event:
              version: 4.0
              id: TMF688
              listener:
                    - POST
              hub:
                    - POST
                    - DELETE
        - ProcessFlowManagement:
            version: 4.0
            id: TMF701
            processFlow:
                - GET
                - GET /id  
    managementAPIs: null
  eventNotification:
    publishedEvent:
        partyInteractionManagement:
        - partyInteractionCreateEvent
        - partyInteractionAttributeValueChangeEvent
        - partyInteractionDeleteEvent
        - partyInteractionStatusChangeEvent 
        processFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
    subscribedEvent:
        partyManagement:
        - organizationCreateEvent
        - organizationAttributeValueChangeEvent
        - organizationStateChangeEvent
        - individualCreateEvent
        - individualAttributeValueChangeEvent
        - individualStateChangeEvent
        partyRoleManagement:
        - partyRoleStateChangeEvent
        documentManagement:
        - documentChangeEvent
        - documentSpecificationAttributeValueChangeEvent
        processFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent           
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
 
  management: []
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  security:
    securitySchemes: []
  selector:
    matchLabels:
      oda.tmforum.org/componentName: PartyInteraction Management
  type: PartyInteraction Management
  version: 1.0.0      

