apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC029-paymentmanagement
  labels:
    oda.tmforum.org/componentName: TMFC029-paymentmanagement
    oda.tmforum.org/funtionalBlockName: Production
spec:
  type: TMFC029-paymentmanagement
  version: 1.1.0
  description: "Payment Management manages methods used by parties to make payments, it also administers payment plan, handles payment or refunds." 
  maintainers:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
  owners:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
coreFunction:
    exposedAPIs:
    - name: PaymentMethods
      id: TMF670
      isRequired: yes
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF670_PaymentMethods/master/TMF670-PaymentMethod-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-PaymentMethods
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentMethods/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentMethods/v4/docs
      port: 8080
      resources: 
       - paymentMethod:
                - GET
                - GET /id
                - POST
                - PATCH
                - DELETE
    - name: PaymentManagement
      id: TMF676
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF676_PaymentManagement/master/TMF676-Payment-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-PaymentManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagement/v4/docs
      port: 8080
      resources: 
       - payment:
                - GET
                - GET /id
                - POST
       - refund:
                - GET
                - GET /id
                - POST

    - name: ProcessFlowManagement
      id: TMF701
      isRequired: not
      version: 4.0
      specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources: 
      - processFlow:
          - POST
          - GET
          - GET /id
          - DELETE
      - taskFlow:
          - PATCH
          - GET
          - GET /id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-PromotionManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources: 
      - event:  
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
    dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-PartyManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
      port: 8080
      resources:  
      - individual:
            - GET 
            - GET /id
      - organization:
            - GET 
            - GET /id
    - name: AccountManagement
      id : TMF666
      isRequired: not
      version: 4.0
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-Account-v4.0.0.swagger.json
      implementation: /{{.Release.Name}}-AccountManagement
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4/docs
      port: 8080
      resources:
        - partyAccount:
                - GET
                - GET /id
        - billingAccount:
                - GET
                - GET /id
        - settlementAccount:
                - GET
                - GET /id
        - financialAccount:
                - GET
                - GET /id
        - billingCycleSpecification:
                - GET
                - GET /id
        - billFormat:
                - GET
                - GET /id
        - billPresentationMedia:
                - GET
                - GET /id
        - name: GeographicAddressManagement
          id: TMF673
          isRequired: not
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.1.swagger.json
          implementation: /{{.Release.Name}}-GeographicAddressManagement
          apitype: openapi
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4/docs
          port: 8080
          resources:
           - geographicAddressValidation:
                - GET
                - GET /id
                - POST
                - PATCH
           - geographicAddress:
                - GET
                - GET /id
           - geographicSubAddress:
                - GET
                - GET /id
        - name: GeographicSiteManagement
          id: TMF674
          isRequired: not
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF674_GeographicSite/master/TMF674-GeographicSite-v4.0.0.swagger.json
          implementation: /{{.Release.Name}}-GeographicSiteManagement
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4/docs
          port: 8080
          resources:
          - geographicSite:
                - GET
                - GET /id
        - name: GeographicLocation
        - id: TMF675
          isRequired: not
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF675_GeographicLocation/master/TMF675-GeographicLocation-v4.0.0.swagger.json
          implementation: /{{.Release.Name}}-GeographicLocation
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4/docs
          port: 8080
          resources: 
          - geographicLocation:
                - GET
                - GET /id
                - POST
                - PATCH
                - DELETE        
        - name: Event 
          id: TMF688
          isRequired: not
          version: 4.0
          specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json      
          apitype: openapi     
          resources: 
          - event:
            - GET
            - GET /id                                  
    publishedEvents: 

    - name: PaymentManagement
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF676_PaymentManagement/master/TMF676-Payment-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentManagement/hub
      implementation: /{{.Release.Name}}-PaymentManagement
      apitype: openapi
      port: 80
      -resources: 
        PaymentManagement:
        - PaymentAttributeValueChangeEvent
        - PaymentCreateEvent
        - PaymentDeleteEvent
        - PaymentStatusChangeEvent
        - RefundAttributeValueChangeEvent
        - RefundCreateEvent
        - RefundStatusChangeEvent
    - name: PaymentMethods
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF670_PaymentMethods/master/TMF670-PaymentMethod-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PaymentMethods/hub
      implementation: /{{.Release.Name}}-PaymentMethods
      apitype: openapi
      port: 80
      -resources: 
        PaymentMethod:
        - PaymentMethodAttributeValueChangeEvent
        - PaymentMethodCreateEvent
        - PaymentMethodDeleteEvent
        - PaymentMethodStatusChangeEvent

    - name: ProcessFlowManagement
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      apitype: openapi
      port: 80
      -resources: 
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent

    subscribedEvents: 
    - name: ResourceActivationAndConfiguration
      specification: https://open-api.tmforum.org/TMF633-Servicecatalog-v4.0.0.swagger.json
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      port: 80
      implementation: /{{.Release.Name}}-ResourceActivationAndConfiguration
      apitype: openapi
      resources: 
      - ResourceActivationAndConfiguration:
        - resourceCreateEvent
        - resourceAttributeValueChangeEvent
        - resourceStateChangeEvent
        - resourceDeleteEvent
        - monitorCreateEvent
        - monitorStatechangeEvent
        - monitorAttributeValueChange
        - monitorDeleteEvent
      - ResourceFunctionActivationAndConfiguration:
        - MigrateCreateEvent
        - MigrateAttributeValueChangeEvent
        - MigrateStateChangeEvent
        - MigratedeleteEvent
        - HealCreateEvent
        - HealAttributeValueChangeEvent
        - HealStateChangeEvent
        - HealDeleteEvent
        - ScaleCreateEvent
        - ScaleAttributeValueChangeEvent
        - ScaleStateChangeEvent
        - ScaleDeleteEvent
        - ResourceFunctionCreateEvent
        - ResourceFunctionAttributeValueChangeEvent
        - ResourceFunctionStateChangeEvent
        - ResourceFunctionDeleteEvent    
    - name: ServiceCatalogManagement
      specification: https://open-api.tmforum.org/TMF633-Servicecatalog-v4.0.0.swagger.json
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/servicepecification/call-back
      port: 80
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      apitype: openapi
      resources:   
      - ServiceCatalogManagement:
        - serviceSpecificationStateChange
        - serviceSpecificationAttributeValueChangeEvent
        - serviceSpecificationCreateEvent
        - serviceSpecificationDeleteEvent    
      - ResourceCatalog:
        - resourceSpecificationCreateEvent
        - resourceSpecificationChangeEvent
        - resourceSpecificationDeleteEvent         
management: []
reporting: []
security: []
