apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata: null
labels:
- name: TMFC036 - Lead and Opportunity Management
oda.tmforum.org/funtionalBlockName: party
oda.tmforum.org/componentName: Lead and Opportunity Management
spec:
componentKinds:
coreFunction:
exposedAPIs:
  - name: SalesManagement
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF699_SalesManagement/master/TMF699-SalesManagement-v4.0.0.swagger.json
    required: true
    implementation: /{{.Release.Name}}-SalesManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4/docs
    port: 8080
  - name: ProcessFlowManagment
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-ProcessFlowManagment
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagment/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagment/v4/docs
    port: 8080
  - name: Event
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
    port: 8080
dependantAPIs:
  - name: PartyManagemnet
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-PartyManagemnet
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagemnet/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagemnet/v4/docs
    port: 8080
  - name: AccountManagement
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-Account-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-AccountManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4/docs
    port: 8080
  - name: AgreementManagement
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF651_AgreementManagement/master/TMF651-AgreementManagement-v4.0.1.swagger.json
    implementation: /{{.Release.Name}}-AgreementManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AgreementManagement/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AgreementManagement/v4/docs
    port: 8080
  - name: QuoteManagement
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-QuoteManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/QuoteManagement/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/QuoteManagement/v4/docs
    port: 8080
  - name: Event
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
    port: 8080
  - name: ProcessFlowManagement
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701-ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    port: 8080
  - name: ProductOrder
    specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-ProductOrder
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrder/v4/doc
    port: 8080
managementAPIs: 
  - name: ResourceActivationConfiguration
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF702-ResourceActivationConfiguration/master/TMF702-ResourceActivation-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-ResourceActivationConfiguration
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceActivationConfiguration/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceActivationConfiguration/v4/docs
    port: 8080
  - name: ResourceFunctionActivation
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-ResourceFunctionActivation/master/TMF688-ResourceFunctionActivation-v4.0.0.swagger.json
    implementation: /{{.Release.Name}}-ResourceFunctionActivation
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceFunctionActivation/v4
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceFunctionActivation/v4/docs
    port: 8080
eventNotification:
  publishedEvents:
    SalesLead:
      - SalesLeadCreateEvent
      - SalesLeadAttributeValueChangeEvent
      - SalesLeadStateChangeEvent
      - SalesLeadDeleteEvent
    SalesOpportunity:
      - SalesOpportunityCreateEvent
      - SalesOpportunityAttributeValueChangeEvent
      - SalesOpportunityStateChangeEvent
      - SalesOpportunityDeleteEvent
    ProcessFlowManagement:
      - ProcessFlowAttributeValueChangeEvent
      - ProcessFlowCreateEvent
      - ProcessFlowDeleteEvent
      - ProcessFlowSpecificationAttributeValueChangeEvent
      - ProcessFlowSpecificationCreateEvent
      - ProcessFlowSpecificationDeleteEvent
      - ProcessFlowSpecificationStateChangeEvent
      - ProcessFlowStateChangeEvent
      - TaskFlowAttributeValueChangeEvent
      - TaskFlowCreateEvent
      - TaskFlowDeleteEvent
      - TaskFlowInformationRequiredEvent
      - TaskFlowSpecificationAttributeValueChangeEvent
      - TaskFlowSpecificationCreateEvent
      - TaskFlowSpecificationDeleteEvent
      - TaskFlowSpecificationStateChangeEvent
      - TaskFlowStateChangeEvent
  subscribedEvents:
    Individual:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
    Organization:
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
    ProductOffering:
      - ProductOfferingCreateEvent
      - ProductOfferingAttributeValueChangeEvent
      - ProductOfferingStateChangeEvent
      - ProductOfferingDeleteEvent     
    ProductOfferingPrice:
      - ProductOfferingPriceCreateEvent
      - ProductOfferingPriceAttributeValueChangeEvent
      - ProductOfferingPriceStateChangeEvent
      - ProductOfferingPriceDeleteEvent
    ProductOrder:
      - ProductOrderCreateEvent 
      - ProductOrderAttributeValueChangeEvent 
      - ProductOrderDeleteEvent 
      - ProductOrderStateChangeEvent 
      - ProductOrderInformationRequiredEvent
    ProductSpecification:
      - ProductSpecificationCreateEvent
      - ProductSpecificationAttributeValueChangeEvent
      - ProductSpecificationStateChangeEvent
      - ProductSpecificationDeleteEvent    
    Agreement:
      - AgreementCreateEvent
      - AgreementAttributeValueChangeEvent
      - AgreementStateChangeEvent
      - AgreementDeleteEvent       
    AgreementSpecification:
      - AgreementSpecificationCreateEvent
      - AgreementSpecificationAttributeValueChangeEvent
      - AgreementSpecificationStateChangeEvent
      - AgreementSpecificationDeleteEvent
    Quote:
      - QuoteCreateEvent
      - QuoteStateChangeEvent
      - QuoteDeleteEvent
      - QuoteInformationRequiredEvent
      - QuoteAttributeValueChangeEvent       
    PartyRole:
      - PartyRoleCreateEvent
      - PartyRoleAttributeValueChangeEvent
      - PartyRoleStateChangeEvent
      - PartyRoleDeleteEvent
maintainers: 
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
management: []
owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi    
security: null
securitySchemes: []
selector: null
matchLabels: null
type: TMFC-036-Lead and Opportunity Management
version: 1.0.0
