apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  name: TMFC035-partyroles&permissionsmanagement
  labels:
    oda.tmforum.org/componentName: TMFC035-partyroles&permissionsmanagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
spec:
  type: TMFC035-partyroles&permissionsmanagement
  version: 1.1.0
  description: >-
    Party Roles & Permissions ODA-Component specification, from Open-API
    reference implementation.
  maintainers:
    - name: Matteo Destino
      email: matteo.destino@accenture.com
      owners: null
    - name: Matteo Destino
      email: matteo.destino@accenture.com
coreFunction:
  exposedAPIs:
    - name: UserRoleAndPermission
      id: TMF672
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRoleAndPermission/master/TMF672-UserRoleAndPermission-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-userrole&permapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRoleAndPermissionManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRoleAndPermissionManagement/v4/docs
      port: 8080
      resources:
        - permission:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
        - userRole:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
    - name: PartyRoleManagement
      id: TMF669
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRoleManagement/master/TMF672-PartyRoleManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-partyroleapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/v4/docs
      port: 8080
      resources: null
      partyRole:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PromotionManagement'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources:
        - event: null
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
  dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: 'yes'
      version: 4
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - individual:
            - GET
            - GET/id
        - organization:
            - GET
            - GET/id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: not
      version: 4
      specification: >-
        ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - processFlow:
            - POST
            - GET
            - GET /id
            - DELETE
        - taskFlow:
            - PATCH
            - GET
            - GET /id
    - name: Event
      id: TMF688
      isRequired: not
      version: 4
      specification: >-
        https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - event:
            - GET
            - GET /id
  publishedEvents:
    - name: userRole
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRoleAndPermission/master/TMF672-UserRoleAndPermission-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-userrole&permapi'
      apitype: openapi
      port: 80
      resources:
        permission:
          - permissionCreateEvent
          - permissionAttributeValueChangeEvent
          - permissionStateChangeEvent
          - permissionDeleteEvent
        userRole:
          - userRoleCreateEvent
          - userRoleAttributeValueChangeEvent
          - userRoleStateChangeEvent
          - userRoleDeleteEvent
    - name: partyRole
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRoleManagement/master/TMF672-PartyRoleManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-partyroleapi'
      apitype: openapi
      port: 80
      resources:
        partyRole:
          - PartyRoleCreateEvent
          - PartyRoleAttributeValueChangeEvent
          - PartyRoleStateChangeEvent
          - PartyRoleDeleteEvent
  subscribedEvents:
    - name: PartyManagement
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PartyManagement'
      apitype: openapi
      port: 80
      resources:
        - organizationCreateEvenet
        - organizationAttributeValueChangeEvent
        - organizationStateChangeEvent
        - individualCreateEvent
        - individualAttributeValueChangeEvent
        - individualStateChangeEvent
    - name: ProcessFlowManagement
      specification: >-
        ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-ProcessFlowManagement'
      apitype: openapi
      port: 80
      resources:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
management: []
reporting: []
security: []
