apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentId: TMFC024
  componentName: BillingaAcountManagement
  componentFunctionalBlock: PartyManagement 
  componenentDescription: "The billing account management component aims to provide all the needed functionalities to create, configure and modify billing accounts. BAM component has the goal to support and handle the following capabilities/ functionalities. Set-up/ creation of Billing account. Associate payment plan(s). Associate payment method(s) - optional. Account taxes/ fees exception management. Define account associations. Provide account balance details. Set-up Billing contacts. Set-up Billing preferences (e.g., bill cycle frequency, invoice media type, invoice template option, etc.)"
  componentVersion: 1.1.0
  componentStatus: specified 
  componentPublicationDate: 2023-08-18
  maintainers:
    - name: Matteo Destino
      email: matteo.destino@accenture.com
  owners: 
    - name: Matteo Destino
      email: matteo.destino@accenture.com
coreFunction:
  exposedAPIs:
    - name: AccountManagement
      id: TMF666
      isRequired: yes
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-accmngt'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4/docs
      port: 8080
      resources:
        - partyAccount:
            - GET
            - GET/id
            - POST
            - PATCH/id
            - DELETE/id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: no
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-procmngttapi'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      port: 8080
      resources:
        - processFlow:
            - GET
            - GET/id
            - POST
            - DELETE/id
        - taskFlow:
            - GET
            - GET/id
            - PATCH/id
    - name: Event
      id: TMF688
      isRequired: no
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-PromotionManagement'
      apitype: openapi
      path: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      developerUI: >-
        /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      port: 8080
      resources:
        - event:
            - GET
            - GET /id
            - POST
            - PATCH
            - DELETE
  dependantAPIs:
    - name: PartyManagement
      id: TMF632
      isRequired: yes
      version: 4.0
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - individual:
            - GET
            - GET/id
        - organization:
            - GET
            - GET/id
    - name: PartyRoleManagement
      id: TMF669
      isRequired: yes
      version: 4.0
      specification: >-
        https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - partyRole:
            - GET
            - GET /id
    - name: UserRolePermission
      id: TMF672
      isRequired: yes
      version: 4.0
      specification: >-
        https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - permission:
            - GET
            - GET /id
        - userRole:
            - GET
            - GET /id
    - name: PaymentMethodManagement
      id: TMF670
      isRequired: yes
      version: 4.0
      specification: >-
        https://github.com/tmforum-apis/TMF670-PaymentMethodManagement/blob/master/TMF670-PaymentMethodManagement-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - paymentMethod:
            - GET
            - GET /id
    - name: ProcessFlowManagement
      id: TMF701
      isRequired: no
      version: 4.0
      specification: >-
        ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - processFlow:
            - POST
            - GET
            - GET /id
            - DELETE
        - taskFlow:
            - PATCH
            - GET
            - GET /id
    - name: Event
      id: TMF688
      isRequired: no
      version: 4.0
      specification: >-
        https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      apitype: openapi
      resources:
        - event:
            - GET
            - GET /id
  publishedEvents:
    - name: AccountManagement
      specification: >-
        https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
      implementation: '/{{.Release.Name}}-accmngt'
      apitype: openapi
      port: 80
      resources:
        Account:
        - partyAccountAttributeValueChangeEvent
        - partyAccountStateChangeEvent
        - billingAccountAttributeValueChangeEvent
        - billingAccountStateChangeEvent
  subscribedEvents:
    - name: PartyRoleManagement
      specification: >-
        https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      apitype: openapi
      port: 80
      resources:
        partyRole
        - partyRoleCreateEvent
        - partyRoleAttributeValueChangeEvent
        - partyRoleStateChangeEvent
        - partyRoleDeleteEvent
        - UserRoleChangeNotification
    - name: UserRoleandPermission
      specification: >-
        https://github.com/tmforum-apis/TMF672-UserRoleandPermission/blob/master/TMF672-UserRoleandPermission-v4.0.0.swagger.json
      apitype: openapi
      port: 80
      resources:
        partyRole
        - partyRoleCreateEvent
        - partyRoleAttributeValueChangeEvent
        - partyRoleStateChangeEvent
        - partyRoleDeleteEvent
        - UserRoleChangeNotification
management: []
reporting: []
security: []
